In [1]:
import numpy as np

In [3]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expense=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit=revenue-expense

In [5]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:

price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
total_cost=np.dot(price_per_unit,units)

In [8]:
total_cost

array([34400, 50000, 64400])

Exercise

In [9]:
Revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [10]:
Revenue_inr=Revenue*np.array([75])

In [11]:
Revenue_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])